cus_subscription_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: pzsuatd-mx13590
      user: Oamen
      password: Ader1234#
      role: oamen_dbt_role
      warehouse: dbt_wh
      database: customer_subscription
      schema: dbt_outputs
      threads: 10
